version: '3.5'
networks:
  web: { external: true }
services:
  traefik:
    image: 'traefik:2.0'
    command:
      - "--log.level=DEBUG"
    restart: 'always'
    ports:
      - '8090:8090'
      - '8888:8080' # Traefik dashboard
      - '443:443'
    # labels: 
    #   - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
    #   - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
    #   - "traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.yml:/etc/traefik/traefik.yml:ro'
      - './dynamic.yml:/etc/traefik/dynamic.yml:ro'
      - './cert/server.key:/etc/traefik/cert/server.key:ro'
      - './cert/server.crt:/etc/traefik/cert/server.crt:ro'
    networks:
      default: {}
      web: {}
  nodejs:
    build: nodejs/
    restart: 'always'
    labels: 
      - traefik.http.routers.nodejs.rule=Host(`localhost`) && Path(`/node`)
      - traefik.http.routers.nodejs.entrypoints=web,websecure
      - traefik.http.routers.nodejs.tls=true
      # - traefik.http.routers.nodejs.tls.certresolver=leresolver
    ports:
      - "9000:9000"
    networks:
      default: {}
      web: {}
  nginx:
    image: nginx
    restart: 'always'
    labels: 
      - traefik.http.routers.nginx.rule=Path(`/nginx`)
      - traefik.http.routers.nginx.entrypoints=web,websecure
      - traefik.http.routers.nginx.tls=true
    networks:
      default: {}
      web: {}
