global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: "DEBUG"

defaultEntryPoints:
  - https
  - http

entryPoints:
  web:
    address: ":8090"
  websecure:
    address: ":443"

providers:
  docker: {}
    # endpoint: "unix:///var/run/docker.sock"
    # exposedByDefault: false
    # network: 'web'
  file:
   filename: '/etc/traefik/dynamic.yml'
   watch: true

api:
  insecure: true
  dashboard: true


# certificatesResolvers:
#   leresolver:
#     acme:
#       email: 'juri.kostik@gmail.com'
#       storage: '/etc/traefik/acme.json'
#       # onHostRule: true
#       httpChallenge:
#         entryPoint: web


# debug: false
# logLevel: ERROR
# defaultEntryPoints:
#   - https
#   - http
# entryPoints:
#   http:
#     address: ':80'
#     redirect:
#       entryPoint: https
#   https:
#     address: ':443'
#     tls: {}
# retry: {}
# docker:
#   endpoint: 'unix:///var/run/docker.sock'
#   domain: my-awesome-app.org
#   watch: true
#   exposedByDefault: false
# acme:
#   email: your-email-here@my-awesome-app.org
#   storage: acme.json
#   entryPoint: https
#   onHostRule: true
#   httpChallenge:
#     entryPoint: http
