global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: "DEBUG"

defaultEntryPoints:
  - https
  - http

entryPoints:
  web:
    address: ":8090"
  websecure:
    address: ":443"

providers:
  docker: {}
  file:
   filename: '/etc/traefik/dynamic.yml'
   watch: true

api:
  insecure: true
  dashboard: true
